import Header from "@/Components/Header"
import "./globals.css"
import type { Metadata } from "next"
import { inter } from "./fonts"
import Footer from "@/Components/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*  <Header /> */}
        {children}
        {/*    <Footer /> */}
      </body>
    </html>
  )
}
